### ISSUE TITLE
:1st_place_medal: delete --allコマンドを削除する

### ISSUE THREAD

**Issue by HidemaruOwO** [HidemaruOwO/pummit#11]
### 新機能及び改善など

delete --allコマンドを削除する

### 詳細

resetとdelete --allの区別が難しいため

**Comment by Comamoca** [comment]
pummitのコマンドライン引数は[当該コミット](https://github.com/Comamoca/pummit/commit/784115db175a472eb76c09a8f4088051d79289f3)で廃止されているため、既に削除されています。よって、`delete --all`コマンドを削除する必要はありません。
